name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ secrets.SERVER_DOCKER }}
        username: ${{ secrets.LOGIN_DOCKER }}
        password: ${{ secrets.PASSWORD_DOCKER }}           
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag client-for-bot:${{github.run_number}}
    - name: Create tag
      run: docker image tag client-for-bot:${{github.run_number}} ${{ secrets.SERVER_DOCKER }}/client-for-bot:latest
    - name: Push image
      run: docker push ${{ secrets.SERVER_DOCKER }}/client-next:latest
